server:
  port: 8080

spring:
  datasource:
    schema: classpath:schema.sql
    data: classpath:data.sql
    url: jdbc:h2:file:~/test
    username: san
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      settings:
        web-allow-others: true
        trace: true
      enabled: true
      path: /myH2
  redis:
    host: localhost
    port: 6379
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true

#apollo
app:
  id: DesignParttenLearning
apollo:
  meta: http://127.0.0.1:8080
  bootstrap:
    enabled: true
    eagerLoad:
      enabled: true
  cacheDir: D:\\data\\apollo-cache
logging:
  level:
    com: info