server:
  port: 8080

spring:
  datasource:
    schema: classpath:schema.sql
    data: classpath:data.sql
    url: jdbc:h2:file:~/test
    username: san
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      settings:
        web-allow-others: true
        trace: true
      enabled: true
      path: /h2-console
  redis:
    host: localhost
    port: 6379